on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/fedora.yml
      - build-aux/meson/**
      - data/**
      - po/**
      - src/**
      - subprojects/**
      - vapi/**
      - meson.build
      - meson_options.txt

  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/fedora.yml
      - build-aux/**
      - data/**
      - po/**
      - src/**
      - subprojects/**
      - vapi/**
      - meson.build
      - meson_options.txt

name: Fedora

jobs:
  build:
    name: Build the app
    runs-on: ubuntu-20.04
    container: nahuelwexd/replay-ci-image:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.2

      - name: Build
        run: |
          meson build -Dprofile=development
          ninja -C build
