on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/flatpak.yml
      - build-aux/flatpak/**
      - build-aux/meson/**
      - data/**
      - po/**
      - src/**
      - subprojects/**
      - vapi/**
      - meson.build
      - meson_options.txt

  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/flatpak.yml
      - build-aux/flatpak/**
      - build-aux/meson/**
      - data/**
      - po/**
      - src/**
      - subprojects/**
      - vapi/**
      - meson.build
      - meson_options.txt

name: Flatpak

jobs:
  build:
    name: Build the app
    runs-on: ubuntu-20.04
    container:
      image: nahuelwexd/replay-ci-image:latest
      options: --privileged
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Cache dependencies
        uses: actions/cache@v2.1.3
        with:
          path: .flatpak-builder
          key: ${{ runner.os }}-flatpak-${{ hashFiles('**/com.github.nahuelwexd.Replay.yml') }}
          restore-keys: |
            ${{ runner.os }}-flatpak-

      - name: Build
        run: |
          flatpak-builder --repo=repo --install-deps-from=gnome-nightly flatpak_app \
              build-aux/flatpak/com.github.nahuelwexd.Replay.yml

      - name: Upload Flatpak repository
        uses: actions/upload-artifact@v2.2.1
        with:
          name: repo
          path: repo

  package:
    name: Create Flatpak bundle
    runs-on: ubuntu-20.04
    container:
      image: nahuelwexd/replay-ci-image:latest
      options: --privileged
    needs: build
    steps:
      - name: Download Flatpak repository
        uses: actions/download-artifact@v2.0.6

      - name: Create Flatpak bundle
        run: |
          flatpak build-bundle repo com.github.nahuelwexd.Replay.Devel.flatpak com.github.nahuelwexd.Replay.Devel
          flatpak build-bundle --runtime repo com.github.nahuelwexd.Replay.Devel.Locale.flatpak \
              com.github.nahuelwexd.Replay.Devel.Locale

      - name: Upload bundle
        uses: actions/upload-artifact@v2.2.1
        with:
          name: Flatpak Bundles
          path: '*.flatpak'
